config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  # sessions: 'public/guest_sign_in'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


# 一致するルートがないとエラー→→URL、ルーティングの問題だった。
  devise_scope :end_user do
    post 'endusers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  namespace :admin do
    root to: 'endusers#index'

    resources :endusers, only:[:show, :edit, :update, :destroy]

    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]

     # 検索機能ルーティング
     get "search" => "searches#search"

  end


  #共通トップ画面のルートパス
    root to: 'public/homes#top'
    get "about"=>"public/homes#about"



  # namespace :public do
   scope module: :public do

    get "mypage"=>"endusers#mypage" 

    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
      member do
       get :favorites
      end
    end


    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites,only:[:create, :destroy]
    end




  # 検索機能ルーティング
  get "search" => "searches#search"

  # タグ検索機能用ルーティング
   get "search_tag"=>"posts#search_tag"

  # 退会確認用ルーティング
   get 'endusers/:id/quit' => 'endusers#quit', as: 'quit'

   # 論理削除用のルーティング
   patch 'endusers/:id/withdrawal' => 'endusers#withdrawal', as: 'withdrawal'
  end

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @model = params[:model]      #検索モデルの定義
    @content = params[:content]  #検索内容の定義
    @method = params[:method]    #検索方法(メソッド)の定義

    @range = params[:range]

    if @range == "Post"
       @posts = Post.looks(params[:search], params[:word])   # looks=searchesとwordsの引数を受け取る(モデルで)
    elsif @range == "EndUser"
      @endusers = EndUser.looks(params[:search], params[:word])
    else
      @comments = PostComment.looks(params[:search], params[:word])
    end
    # byebug
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search_form.html.erb
<% if admin_signed_in? %>
  <div class="search_form">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["投稿","Post"], ["会員","EndUser"],["コメント","PostComment"]]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/searches/search.html.erb
<div class="container">
 <h2>検索結果</h2>
  <div class="row">
   <table class="table table-hover table-inverse">
    <!--検索対象モデルがEndUserの時 -->
     <% if @range == "Post" %>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title,admin_post_path(post.id) %></td>
            <td><%= post.end_user.nickname %></td>
          </tr>
        <% end %>
      </tbody>
     <% elsif @range == "EndUser" %>
      <!--検索対象モデルがPostではない時(=検索対象モデルがEndUserの時) -->
      <tbody>
        <% @endusers.each do |enduser| %>
          <tr>
            <td><%= link_to enduser.nickname,admin_enduser_path(enduser.id) %></td>
          </tr>
        <% end %>
      </tbody>
     <% else %>
     <!--検索対象モデルがEndUserでもPostない時(=検索対象モデルがPostCommentの時) -->
     <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= link_to comment.comment,admin_post_comment_path(comment.id) %></td>
            <td><%= link_to comment.end_user.nickname %>
          </tr>
        <% end %>
      </tbody>
    <% end %>
   </table>
 </div>
</div>