config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  # sessions: 'public/guest_sign_in'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


# 一致するルートがないとエラー→→URL、ルーティングの問題だった。
  devise_scope :end_user do
    post 'endusers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  namespace :admin do
    root to: 'endusers#index'

    resources :endusers, only:[:show, :edit, :update, :destroy]

    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]

     # 検索機能ルーティング
     get "search" => "searches#search"

  end


  #共通トップ画面のルートパス
    root to: 'public/homes#top'
    get "about"=>"public/homes#about"



  # namespace :public do
   scope module: :public do

    get "mypage"=>"endusers#mypage" 

    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
      member do
       get :favorites
      end
    end


    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites,only:[:create, :destroy]
    end




  # 検索機能ルーティング
  get "search" => "searches#search"

  # タグ検索機能用ルーティング
   get "search_tag"=>"posts#search_tag"

  # 退会確認用ルーティング
   get 'endusers/:id/quit' => 'endusers#quit', as: 'quit'

   # 論理削除用のルーティング
   patch 'endusers/:id/withdrawal' => 'endusers#withdrawal', as: 'withdrawal'
  end

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


 #ゲストログインの設定
 def new_guest
  enduser = EndUser.find_or_create_by!(email: 'guest@example.com') do |enduser|   # find_or_create_by =条件を指定して初めの1件を取得し1件もなければ作成する

   enduser.nickname = guest
   enduser.password = SecureRandom.urlsafe_base64     # パスワードをランダム生成させるメソッド
 end
end

def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = "guest"
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
end



# アソシエーション
  has_many :posts, dependent: :destroy

  has_many :post_comments,dependent: :destroy

  has_many :favorites,dependent: :destroy


# Active storageの設定
  has_one_attached :profile_image


 # バリデーション
  validates :nickname, presence: true,length: { maximum: 15 }


 # 退会後に、同じアカウントでログインできないようにする処理
  def active_for_authentication?
    super && (is_deleted == false)
  end


# 検索方法の分岐
def self.looks(search, word)
   if search == "perfect_match"
      @enduser = EndUser.where("nickname LIKE?", "#{word}") # 完全一致
   elsif search == "forward_match"
      @enduser = EndUser.where("nickname LIKE?","#{word}%")  #前方一致
   elsif search == "backward_match"
      @enduser = EndUser.where("nickname LIKE?","%#{word}") #後方一致
   elsif search == "partial_match"
      @enduser = EndUser.where("nickname LIKE?","%#{word}%") #部分一致
   else
      @enduser = EndUser.all
   end
end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
 def index
    @endusers = EndUser.all
  end

  def show
    # @enduser = EndUser.find(params[:id])
  end

  def edit
    # @enduser = EndUser.find(params[:id])
  end

  def update
    # @enduser = EndUser.find(params[:id])
    # if @enduser.update(enduser_params)
    #   redirect_to admin_enduser_path(@enduser.id)
    # else
    #   render "edit"
    # end
  end

  def destroy
  end

  def enduser_params
     params.require(:enduser).permit(:nickname, :email, :is_deleted)
  end


end

app/controllers/admin/enduser_controller.rb
class Admin::EnduserController < ApplicationController
  def index
    @endusers = Endusers.all
  end
  
  def show
    @enduser = Enduser.find(params[:id])
  end
  
  def edit
  end
  
  def destroy
  end
  
end

app/controllers/admin/endusers_controller.rb
class Admin::EndusersController < ApplicationController

  def index
    @endusers = EndUser.all.page(params[:page]).per(10)
  end

  def show
     @enduser = EndUser.find(params[:id])
  end

  def edit
    @enduser = EndUser.find(params[:id])
  end

  def update
    @enduser = EndUser.find(params[:id])
    if @enduser.update(enduser_params)
      redirect_to admin_enduser_path(@enduser.id)
    else
      render "edit"
    end
  end

  def destroy
  end

  def enduser_params
     params.require(:end_user).permit(:nickname, :email, :is_deleted)
  end
end

app/helpers/admin/enduser_helper.rb
module Admin::EnduserHelper
end

app/helpers/admin/endusers_helper.rb
module Admin::EndusersHelper
end

app/views/admin/endusers/edit.html.erb
<% if flash[:notice] %>
 <div class="alert alert-success" role="alert">
 <p class="notice text-center" style="color:red;"><%= flash[:notice] %></p></div>
<% end %>

<%= form_with model: @enduser, url: admin_enduser_path(@enduser.id), method: :patch do |f| %>
<div class = "container">
  <div class ="row">
    <h3 class ="px-5 bg-light">会員編集</h3>
    <table class = "table">
    <thead>
       <td>会員ID</td>
       <td><%= @enduser.id %></td>
      </tr>

      <tr>
       <td>ニックネーム</td>
       <td><%= @enduser.nickname %></td>
      </tr>

      <tr>
        <td>メールアドレス</td>
        <td><%= @enduser.email %></td>
      </tr>


      <tr>
       <td><%= f.label :is_deleted,"会員ステータス" %></td>
       <td>
         <%= f.radio_button :is_deleted, false %>
         <%= f.label :is_deleted, "有効"  %>
         <%= f.radio_button :is_deleted, true %>
         <%= f.label :is_deleted, "無効" %>
       </td>
      </tr>
   </table>
   
   <div class="form-group">
     <%= f.submit '変更を保存', class:"btn btn-success" %>
   </div>
      <% end %>
   <div class="form-group">
     <%= link_to "詳細へ戻る",admin_enduser_path(@enduser.id), class: "btn btn-default" %>
   </div>
 </div>
 

app/views/admin/endusers/index.html.erb
<% if flash[:notice] %>
 <div class="alert alert-success" role="alert">
 <p class="notice text-center" style="color:green;"><%= flash[:notice] %></p></div>
<% end %>

<div class = "container">
  <div class ="row">
   <div class="col-md-8 offset-md-1">
    <h3 class ="px-5 bg-light">会員一覧</h3>
     <table class = "table">
      <thead>
       <tr>
         <td>会員ID</td>
         <td>氏名</td>
         <td>メールアドレス</td>
         <td>ステータス</td>
       </tr>
      </thead>
      <tbody>
        <% @endusers.each do |enduser| %>
         <tr>
          <td><%= enduser.id %></td>
          <td><%= link_to enduser.nickname, admin_enduser_path(enduser.id) %></td>
          <td><%= enduser.email %></td>
          <td>
           <% if enduser.is_deleted == false %>
            <%= '有効' %>
           <% else %>
            <%= '退会' %>
           <% end %>
          </td>
         </tr>
        <% end %>
      </tbody>
     </table>
    <div class="row align-bottom mx-auto">
     <div class="mx-auto">
     <%= paginate @endusers %>
     </div>
    </div>
  </div>

app/views/admin/endusers/show.html.erb
 <div class = "container">
  <div class ="row">
    <h3 class ="px-5 bg-light">会員詳細</h3>
    <table class = "table">
    <thead>
   <tr>
    <td>会員ID</td>
    <td><%= @enduser.id %></td>
   </tr>

    <tr>
     <td>ニックネーム</td>
     <td><%= @enduser.nickname %></td>
    </tr>
    
    <tr>
     <td>メールアドレス</td>
     <td><%= @enduser.email %></td>
    </tr>

    <tr>
     <td>会員ステータス</td>
      <td>
       <% if @enduser.is_deleted == false %>
         <p class="text-success"><%= '有効' %></p>
       <% else %>
         <p class="text-secondary"><%= '退会' %></p>
       <% end %>
      </td>
     </tr>
    </thead>
  </table>
 </div>

<div class="row">
 <div class="mx-auto py-5 mr-5 justify-content-center">
  <%= link_to "編集する",edit_admin_enduser_path(@enduser.id),class: "btn btn-info" %>
  <%= link_to "会員一覧へ",admin_root_path, class: "btn btn-primary" %>
 </div>
</div>