config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  # sessions: 'public/guest_sign_in'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


# 一致するルートがないとエラー→→URL、ルーティングの問題だった。
  devise_scope :end_user do
    post 'endusers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  namespace :admin do
    root to: 'endusers#index'

    resources :endusers, only:[:show, :edit, :update, :destroy]

    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]

     # 検索機能ルーティング
     get "search" => "searches#search"

  end


  #共通トップ画面のルートパス
    root to: 'public/homes#top'
    get "about"=>"public/homes#about"



  # namespace :public do
   scope module: :public do

    get "mypage"=>"endusers#mypage" 

    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
      member do
       get :favorites
      end
    end


    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites,only:[:create, :destroy]
    end




  # 検索機能ルーティング
  get "search" => "searches#search"

  # タグ検索機能用ルーティング
   get "search_tag"=>"posts#search_tag"

  # 退会確認用ルーティング
   get 'endusers/:id/quit' => 'endusers#quit', as: 'quit'

   # 論理削除用のルーティング
   patch 'endusers/:id/withdrawal' => 'endusers#withdrawal', as: 'withdrawal'
  end

end

app/views/layouts/_admin_header.html.erb
 <header class="shadow-sm">
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
     <a class="navbar-brand" href="/"><%= image_tag asset_path('PF_header_logo.png') %></a>
       <div class="search">
         <%= render "admin/searches/search_form" %>
       </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
         
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav md-auto">
           <% if admin_signed_in? %>
            <li>
             <%= link_to "会員一覧", admin_root_path, class: "nav-link"%>
             </li>
             <li>
              <%= link_to "会員投稿一覧", admin_posts_path, class: "nav-link" %>
             </li>
             <li>
               <%= link_to "会員コメント一覧", admin_post_comments_path, class: "nav-link" %>
             </li>
             </li>
             <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
             </li>
          <% else %>
             <li>
               <%= link_to"トップページへ", root_path, class:"link"  %>
            </li>
             <li>
               <%= link_to"サインアップ", "/end_users/sign_up",class:"link" %>
             </li>
             <li>
               <%= link_to"ログイン", "/end_users/sign_in",  class:"link" %>
            </li>
          
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_enduser_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
     <a class="navbar-brand" href="/"><%= image_tag asset_path('PF_header_logo.png') %></a>

       <div class="search">
          <%= render "public/searches/search_form" %>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if end_user_signed_in? %>
          <li>
            <%= link_to "メニュー",mypage_path, data: {"turbolinks" => false},class: "nav-link" %>
            <!--ターボリンクスの設定、ページ遷移をAjax(非同期通信)に置き換え、JavaScriptやCSSのパースを省略することで高速化するgemの一種。Rails4以降でデフォルトで設定されている-->
          </li>
          <li>
            <%= link_to "新規投稿",new_post_path,data: {"turbolinks" => false},class: "nav-link" %>
          </li>
          <li>
            <%= link_to "マイページ", enduser_path(current_end_user.id), class: "nav-link" %>
          </li>
          <li>
            <%= link_to "アカウント編集",edit_enduser_path(current_end_user.id),data: {"turbolinks" => false},class: "nav-link" %>
          </li>
          <li>
            <%= link_to "投稿一覧",posts_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "退会する",quit_path(current_end_user.id),class: "nav-link" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li>
            <%= link_to"トップページへ",root_path, class:"link" %>
          </li>
          <li>
            <%= link_to"サインアップ", "/end_users/sign_up", class:"link" %>
          </li>
          <li>
            <%= link_to"ログイン", "/end_users/sign_in", class:"link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<footer class="shadow-sm">
<div class="container">
 <div class="row">
  <div class="mx-auto mt-3 footer-bottom text-center">
   <p>©︎share-tabi.com</p>
  </div>
 </div>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareTabi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--画像のプレビュー用に追加--->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!--ここまで-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

 <body class="d-flex flex-column">

    <% if admin_signed_in? %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/enduser_header" %>
    <% end %>
     <main>
　　    <%= yield %>
    </main>
  </body>

<footer>
  <%= render "layouts/footer" %>
</footer>

</html>